kanban/kanban/urls.py
from django.contrib import admin
from django.urls import path, include

from kanban.views import home_page, login_page, signup_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_page, name='login-page'),
    path('signup/', signup_page),
    path('home/', home_page),
    path('api/', include(('task_board.urls', 'task_board'), namespace='task_board')),
]

kanban/task_board/urls.py
from django.urls import path

from task_board.views import UserAPIView, UserLoginAPIView

urlpatterns = [
    path('user/', UserAPIView.as_view(), name='user'),
    path('login/', UserLoginAPIView.as_view(), name='user-login'),
]

kanban/task_board/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

GENDER_CHOICES = (
    ('M', 'Male'),
    ('F', 'Female')
)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="user_profile")
    profile_pic = models.ImageField(upload_to='images/', blank=True, null=True)
    gender = models.CharField(max_length=2, choices=GENDER_CHOICES)
    verified = models.BooleanField(default=False)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, raw, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

kanban/kanban/views.py
from django.shortcuts import render


def home_page(request):
    return render(request, "home.html")


def login_page(request):
    return render(request, "login.html")


def signup_page(request):
    return render(request, "signup.html")

kanban/task_board/views.py
from django.http import JsonResponse
from rest_framework import generics
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from rest_framework.status import HTTP_200_OK, HTTP_400_BAD_REQUEST
from rest_framework.views import APIView

from task_board.login_signup_serializer import UserSerializer, User, UserLoginSerializer


class UserAPIView(generics.ListAPIView, generics.CreateAPIView):
    serializer_class = UserSerializer
    queryset = User.objects.all()

    def create(self, request, *args, **kwargs):
        user = UserSerializer(data=request.data)
        if user.is_valid():
            user.save()
            return Response(user.data)
        return Response(user.errors, status=HTTP_400_BAD_REQUEST)


class UserLoginAPIView(APIView):
    permission_classes = [AllowAny]
    serializer_class = UserLoginSerializer

    def post(self, request, *args, **kwargs):
        data = request.data
        serializer = UserLoginSerializer(data=data)

        if serializer.is_valid(raise_exception=True):
            new_data = serializer.data
            return Response(new_data, status=HTTP_200_OK)
        return Response(serializer.errors, status=HTTP_400_BAD_REQUEST)

kanban/templates/base.html
<!doctype html>
{% load static %}
{% load widget_tweaks %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.1/dist/jquery.validate.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.1/dist/additional-methods.min.js"></script>

    <title>{{ title }}</title>
</head>
<body style="background-image: linear-gradient(to top, #cbcfd5, #abaeb3, #8c8d92, #6e6e73, #515155);">
<div style="height: 100vh">
    <div class="container my-auto h-100">

        {% block content %}

        {% endblock %}

    </div>
</div>

{% block javascript %}

{% endblock %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

<script>
    let user_api_url = "{% url 'task_board:user' %}";
    let login_api_url = "{% url 'task_board:user-login' %}";
    let login_page_url = "{% url 'login-page' %}"
</script>

<script type="text/javascript" src="{% static 'js/login_signup.js' %}"></script>

</body>
</html>

kanban/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"
          id="bootstrap-css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description"
          content="Responsive sidebar template with sliding effect and dropdown menu based on bootstrap 3">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <title>Task Board</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
</head>

<body>
<div class="page-wrapper chiller-theme toggled">
    <a id="show-sidebar" class="btn btn-sm btn-dark" href="#">
        <i class="fas fa-bars"></i>
    </a>
    <nav id="sidebar" class="sidebar-wrapper">
        <div class="sidebar-content">
            <div class="sidebar-brand">
                <a href="#">pro sidebar</a>
                <div id="close-sidebar">
                    <i class="fas fa-times"></i>
                </div>
            </div>
            <div class="sidebar-header">
                <div class="user-pic">
                    <img class="img-responsive img-rounded"
                         src="https://raw.githubusercontent.com/azouaoui-med/pro-sidebar-template/gh-pages/src/img/user.jpg"
                         alt="User picture">
                </div>
                <div class="user-info">
          <span class="user-name">Jhon
            <strong>Smith</strong>
          </span>
                    <span class="user-role">Administrator</span>
                    <span class="user-status">
            <i class="fa fa-circle"></i>
            <span>Online</span>
          </span>
                </div>
            </div>
            <!-- sidebar-header  -->
            <div class="sidebar-search">
                <div>
                    <div class="input-group">
                        <input type="text" class="form-control search-menu" placeholder="Search...">
                        <div class="input-group-append">
              <span class="input-group-text">
                <i class="fa fa-search" aria-hidden="true"></i>
              </span>
                        </div>
                    </div>
                </div>
            </div>
            <!-- sidebar-search  -->
            <div class="sidebar-menu">
                <ul>
                    <li class="header-menu">
                        <span>General</span>
                    </li>
                    <li class="sidebar-dropdown">
                        <a href="#">
                            <i class="fa fa-tachometer-alt"></i>
                            <span>Dashboard</span>
                            <span class="badge badge-pill badge-warning">New</span>
                        </a>
                        <div class="sidebar-submenu">
                            <ul>
                                <li>
                                    <a href="#">Dashboard 1
                                        <span class="badge badge-pill badge-success">Pro</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">Dashboard 2</a>
                                </li>
                                <li>
                                    <a href="#">Dashboard 3</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="sidebar-dropdown">
                        <a href="#">
                            <i class="fa fa-shopping-cart"></i>
                            <span>E-commerce</span>
                            <span class="badge badge-pill badge-danger">3</span>
                        </a>
                        <div class="sidebar-submenu">
                            <ul>
                                <li>
                                    <a href="#">Products

                                    </a>
                                </li>
                                <li>
                                    <a href="#">Orders</a>
                                </li>
                                <li>
                                    <a href="#">Credit cart</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="sidebar-dropdown">
                        <a href="#">
                            <i class="far fa-gem"></i>
                            <span>Components</span>
                        </a>
                        <div class="sidebar-submenu">
                            <ul>
                                <li>
                                    <a href="#">General</a>
                                </li>
                                <li>
                                    <a href="#">Panels</a>
                                </li>
                                <li>
                                    <a href="#">Tables</a>
                                </li>
                                <li>
                                    <a href="#">Icons</a>
                                </li>
                                <li>
                                    <a href="#">Forms</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="sidebar-dropdown">
                        <a href="#">
                            <i class="fa fa-chart-line"></i>
                            <span>Charts</span>
                        </a>
                        <div class="sidebar-submenu">
                            <ul>
                                <li>
                                    <a href="#">Pie chart</a>
                                </li>
                                <li>
                                    <a href="#">Line chart</a>
                                </li>
                                <li>
                                    <a href="#">Bar chart</a>
                                </li>
                                <li>
                                    <a href="#">Histogram</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="sidebar-dropdown">
                        <a href="#">
                            <i class="fa fa-globe"></i>
                            <span>Maps</span>
                        </a>
                        <div class="sidebar-submenu">
                            <ul>
                                <li>
                                    <a href="#">Google maps</a>
                                </li>
                                <li>
                                    <a href="#">Open street map</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="header-menu">
                        <span>Extra</span>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-book"></i>
                            <span>Documentation</span>
                            <span class="badge badge-pill badge-primary">Beta</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-calendar"></i>
                            <span>Calendar</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-folder"></i>
                            <span>Examples</span>
                        </a>
                    </li>
                </ul>
            </div>
            <!-- sidebar-menu  -->
        </div>
        <!-- sidebar-content  -->
        <div class="sidebar-footer">
            <a href="#">
                <i class="fa fa-bell"></i>
                <span class="badge badge-pill badge-warning notification">3</span>
            </a>
            <a href="#">
                <i class="fa fa-envelope"></i>
                <span class="badge badge-pill badge-success notification">7</span>
            </a>
            <a href="#">
                <i class="fa fa-cog"></i>
                <span class="badge-sonar"></span>
            </a>
            <a href="#">
                <i class="fa fa-power-off"></i>
            </a>
        </div>
    </nav>
    <!-- sidebar-wrapper  -->
    <main class="page-content">
        <div class="container-fluid">

        </div>

    </main>
    <!-- page-content" -->
</div>
<!-- page-wrapper -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'js/home.js' %}"></script>

</body>

</html>

kanban/templates/login.html
{% extends "base.html" %}

{% block content %}
    <div class="row h-100">
        <div class="card card-login col-lg-4 col-xl-3 my-auto mx-auto responsive_width" style="">

            <div class="card-header">
                <h2 class="text-center header">LOGIN</h2>
            </div>
            <div style="padding-top: 10px">
                <form enctype="multipart/form-data" id="submit-form" method="POST">
                    {% csrf_token %}
                    <div class="form-group label-style">
                        <label for="username">Username:</label>
                        <input type="text" class="form-control" id="username" name='username' required
                               autocomplete="new-password">
                    </div>
                    <div class="form-group label-style" style="padding-top: 10px;">
                        <label for="pwd">Password:</label>
                        <input type="password" class="form-control" id="pwd" name='password' required
                               autocomplete="new-password">
                    </div>
                    <p style="color: white; font-size: 15px;">{{ error_msg }}</p>
                    <div>
                        <div style="float: left; padding-top: 20px; width: 100px;">
                            <input type="submit" class="btn btn-info" value="LOGIN">
                        </div>
                        <div style="float: right; line-height: 10px;">
                            <br><br>
                            <a href="signup"><p style="color: #FFFFFF">Sign up here!</p></a>
                            <a href="#"><p style="color: #FFFFFF">Forgot Password?</p></a>
                        </div>

                    </div>
                </form>

            </div>
        </div>
    </div>

{% endblock %}

kanban/templates/signup.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}

    <div class="row h-100">
        <div class="card card-signup col-lg-12 col-xl-6 my-auto mx-auto responsive_width">
            <div class="card-header">
                <h2 class="text-center header">SIGNUP</h2>
            </div>
            <br>
            <div style="padding-top: 10px">
                <form enctype="multipart/form-data" class="row" id="submit-form" method="POST">
                    {% csrf_token %}

                    <div class="col-md-6 form-group label-style">
                        <label for="first_name">First Name:</label>
                        <input type="text" class="form-control" id="first_name" name='first_name' required
                               autocomplete="new-password">
                    </div>

                    <div class="col-md-6 form-group label-style">
                        <label for="last_name">Last Name:</label>
                        <input type="text" class="form-control" id="last_name" name='last_name' required
                               autocomplete="new-password">
                    </div>

                    <div class="col-md-6 form-group label-style">
                        <label for="username">Username:</label>
                        <input type="text" class="form-control" id="username" name='username' required
                               autocomplete="new-password">
                        <p class="d-none error username"></p>
                    </div>

                    <div class="col-md-6 form-group label-style">
                        <label for="email">Email:</label>
                        <input type="email" class="form-control" id="email" name='email' required
                               autocomplete="new-password">
                        <p class="d-none error email"></p>
                    </div>

                    <div class="col-md-6 form-group label-style">
                        <label for="password">Password:</label>
                        <input type="password" class="form-control" id="password" name='password' required
                               autocomplete="new-password">
                    </div>

                    <div class="col-md-6 form-group label-style">
                        <label for="confirm_password"> Confirm Password:</label>
                        <input type="password" class="form-control" id="confirm_password" name='confirm_password'
                               required
                               autocomplete="new-password">
                    </div>

                    <div class="col-md-6 form-group label-style">
                        <label>Gender: </label><br>
                        <label>MALE:</label>
                        <input type="radio" name='gender' value="M"
                               autocomplete="new-password">
                        <label>FEMALE:</label>
                        <input type="radio" name='gender' value="F"
                               autocomplete="new-password">

                    </div>

                    <div class="col-md-6" style="padding-top: 20px; float: right;">
                        <input type="submit" class="btn btn-info" value="SIGN UP"
                               style="width: 225px;  height: 58px;">
                    </div>


                </form>

            </div>
        </div>
    </div>

{% endblock %}